### ISSUE TITLE
How to install this

### ISSUE THREAD

**Issue by Andrew-Sor** [RyanLua/FluentAutoClicker#3]
How to install this?

**Comment by RyanLua** [comment]
There is no way to install Fluent Auto Clicker since it's still a work in progress and I want some features in it before I release it. The only way to use Fluent Auto Clicker is to compile it using [Visual Studio](https://visualstudio.microsoft.com/). Note that it will be buggy and unfinished since it's still a work in progress.

**Comment by Andrew-Sor** [comment]
It's now clear... Thanks you
